In [1]:
# convert the list into numpy array, then display the array-> 

import numpy as np
my_list = [1,2,3,4,5]

print(np.array(my_list))




[1 2 3 4 5]


In [3]:
# Convert the below list into a numpy array then display the array then display the first
# and last index and then multiply each element by 2 and display the result.

# Input: my list = [1,2,3,4,5]

import numpy as np

mylist = [1,2,3,4,5]

arr = np.array(mylist)

print("First element: ", arr[0])
print("Last element: ", arr[-1])

print("Array after doubling each element: ", arr *2)



First element:  1
Last element:  5
Array after doubling each element:  [ 2  4  6  8 10]


In [7]:
'''1. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives.

Sample Output:

An array of 10 zeros:

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0]

An array of 10 ones

[LLLL. 1. 1. 1. 1. 1. 11

An array of 10 Fives

15. 5. 5. 5. 5. 5. 5. 5. 5.5.1
'''


print("An array of 10 zeros: ")

print(np.zeros(10))

print("An array of 10 ones: ")

print(np.ones(10))

print("An array of 10 fives: ")

print(np.full(10,5))                       # np.full(no.of elements , element)


An array of 10 zeros: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: 
[5 5 5 5 5 5 5 5 5 5]


In [10]:
'''Calculate the total revenue generated by two product categories in a store

Input:

category1 revenue np.array([500, 600, 700, 5501)

category2_revenue = np.array([450, 700, 800, 8001)

Output:

Total Revenue: [950 1300 1500 1150]'''

category1_revenue= np.array([500, 600, 700, 5501])

category2_revenue = np.array([450, 700, 800, 8001])
                              
print(category1_revenue + category2_revenue)
                        

[  950  1300  1500 13502]


In [14]:


'''2. Calculate the profit made by a company

Input:

revenue = np.array([10000, 12000, 11000, 105001]) 
expenses = np.array([4000, 5000 4500, 48001])

Output:

Profit: [6000 7000 6500 5700]'''


revenue = np.array([10000, 12000, 11000, 10500]) 
expenses = np.array([4000, 5000, 4500, 4800])

print("Profit: ", revenue - expenses)

Profit:  [6000 7000 6500 5700]
